export const INITIALIZATION = "INITIALIZATION";
export const ADD_CALL_TO_QUEUE = "ADD_CALL_TO_QUEUE";
export const ELEVATOR_CALL = "ELEVATOR_CALL";
export const ELEVATOR_ARRIVED = "ELEVATOR_ARRIVED";
export const DELAY_OVER = "DELAY_OVER";
